### ISSUE TITLE
Id not specified in an update call

### ISSUE THREAD

**Issue by shaunhardy** [phpforce/soap-client#11]
Applying the fix in #9 exposed a bug in the PHP SOAP library where ```SoapClient::__getTypes()``` does not support extensions in the XMLSchema when used in WSDL mode.

https://bugs.php.net/bug.php?id=45404

Since every object in the WSDL extends ```sObject```, which is where the ```Id``` is declared, any record update will fail with "Id not specified in an update call".

**Comment by mathielen** [comment]
+1

**Comment by technweb** [comment]
See #19

**Comment by ddeboer** [comment]
Should be fixed with #19.
